//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Randomizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mmr_f_sot {
            get {
                object obj = ResourceManager.GetObject("mmr_f_sot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Version&quot;: 24,
        ///  &quot;Logic&quot;: [
        ///    {
        ///      &quot;Id&quot;: &quot;MaskDeku&quot;,
        ///      &quot;RequiredItems&quot;: [],
        ///      &quot;ConditionalItems&quot;: [],
        ///      &quot;TimeNeeded&quot;: &quot;None&quot;,
        ///      &quot;TimeAvailable&quot;: &quot;None&quot;,
        ///      &quot;TimeSetup&quot;: &quot;None&quot;,
        ///      &quot;IsTrick&quot;: false
        ///    },
        ///    {
        ///      &quot;Id&quot;: &quot;ItemBow&quot;,
        ///      &quot;RequiredItems&quot;: [
        ///        &quot;AreaWoodFallTempleAccess&quot;,
        ///        &quot;WFT 2nd Floor Access&quot;
        ///      ],
        ///      &quot;ConditionalItems&quot;: [
        ///        [
        ///          &quot;Any Sword&quot;
        ///        ],
        ///        [
        ///          &quot;OtherArrow&quot;
        ///        ],
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string REQ_CASUAL {
            get {
                return ResourceManager.GetString("REQ_CASUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Version&quot;: 24,
        ///  &quot;Logic&quot;: [
        ///    {
        ///      &quot;Id&quot;: &quot;MaskDeku&quot;,
        ///      &quot;RequiredItems&quot;: [],
        ///      &quot;ConditionalItems&quot;: [],
        ///      &quot;TimeNeeded&quot;: &quot;None&quot;,
        ///      &quot;TimeAvailable&quot;: &quot;None&quot;,
        ///      &quot;TimeSetup&quot;: &quot;None&quot;,
        ///      &quot;IsTrick&quot;: false
        ///    },
        ///    {
        ///      &quot;Id&quot;: &quot;ItemBow&quot;,
        ///      &quot;RequiredItems&quot;: [
        ///        &quot;AreaWoodFallTempleAccess&quot;,
        ///        &quot;WFT 2nd Floor Access&quot;
        ///      ],
        ///      &quot;ConditionalItems&quot;: [],
        ///      &quot;TimeNeeded&quot;: &quot;None&quot;,
        ///      &quot;TimeAvailable&quot;: &quot;None&quot;,
        ///      &quot;TimeSetup&quot;: &quot;None&quot;,
        ///      &quot;Is [rest of string was truncated]&quot;;.
        /// </summary>
        public static string REQ_GLITCH {
            get {
                return ResourceManager.GetString("REQ_GLITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-terminafield
        ///0,102
        ///3
        ///2
        ///mm-snowheadmountains
        ///0,113
        ///15
        ///13
        ///mm-greatbaycoast
        ///0,1,110
        ///1D
        ///10
        ///mm-ikanacanyon
        ///0,1,111
        ///1E
        ///11
        ///mm-southernswamp
        ///0,1,10C
        ///1C
        ///C
        ///mm-clocktown1
        ///1,115
        ///19
        ///15
        ///mm-clocktown2
        ///1,116
        ///19
        ///16
        ///mm-clocktown3
        ///1,117
        ///19
        ///17
        ///mm-goroncity
        ///1,3,130
        ///26
        ///30
        ///mm-romaniranch
        ///0,1,12F
        ///7
        ///2F
        ///mm-zorahall
        ///1,3,136
        ///B
        ///36
        ///mm-dekupalace
        ///1,0,112
        ///19
        ///12
        ///mm-caves
        ///2,13B
        ///1A
        ///3B
        ///mm-snowheadtemple
        ///2,165
        ///15
        ///65
        ///mm-greatbaytemple
        ///2,166
        ///16
        ///66
        ///mm-piratefortress
        ///2,114
        ///3
        ///14
        ///mm- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SEQS {
            get {
                return ResourceManager.GetString("SEQS", resourceCulture);
            }
        }
    }
}
