//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Enemizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Enemizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -actor
        ///-obj
        ///-vars - todo: may connect to switches
        ///-type - 0=ground, 1=water, 2=air, 3=other, 4=respawn
        ///-moving - 0=no, 1=yes
        ///-scene excludes
        ///-octorok
        ///0008
        ///0005
        ///ff00
        ///1
        ///0
        ///13,49
        ///-wallmaster
        ///000a
        ///0009
        ///0001
        ///0
        ///1
        ///
        ///-dodongo
        ///000b
        ///000a
        ///0001,0000
        ///0
        ///1
        ///
        ///-keese
        ///000c
        ///000b
        ///8003,0004,0000
        ///2
        ///1
        ///
        ///-tektite
        ///0012
        ///0012
        ///fffd,fffe,ffff
        ///0
        ///1
        ///
        ///-peahat
        ///0014
        ///0014
        ///0000
        ///0
        ///1
        ///7
        ///-dinolfos
        ///0019
        ///0017
        ///0000
        ///0
        ///1
        ///1b,21,60,66
        ///-shabom
        ///001d
        ///000e
        ///0000
        ///2
        ///1
        ///69
        ///-skulltula
        ///0024
        ///0020
        ///003f,007f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENEMIES {
            get {
                return ResourceManager.GetString("ENEMIES", resourceCulture);
            }
        }
    }
}
