//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Randomizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class asm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal asm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Randomizer.Resources.asm", typeof(asm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DamageModeDoom {
            get {
                object obj = ResourceManager.GetObject("DamageModeDoom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DeathMoonCrash {
            get {
                object obj = ResourceManager.GetObject("DeathMoonCrash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rom_patch {
            get {
                object obj = ResourceManager.GetObject("rom_patch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;DPAD_CONFIG&quot;: &quot;03819CD0&quot;,
        ///    &quot;DPAD_TEXTURE&quot;: &quot;0381C310&quot;,
        ///    &quot;EXT_MSG_DATA_FILE&quot;: &quot;0381A538&quot;,
        ///    &quot;EXT_MSG_TABLE&quot;: &quot;0381BCF8&quot;,
        ///    &quot;EXT_MSG_TABLE_COUNT&quot;: &quot;0381A4C0&quot;,
        ///    &quot;EXT_OBJECTS&quot;: &quot;0381A6BC&quot;,
        ///    &quot;FONT_TEXTURE&quot;: &quot;0381D310&quot;,
        ///    &quot;G_C_HEAP&quot;: &quot;03820000&quot;,
        ///    &quot;G_KALEIDOPAYLOAD_ADDR&quot;: &quot;03880000&quot;,
        ///    &quot;G_PAYLOAD_ADDR&quot;: &quot;03800000&quot;,
        ///    &quot;HASH_ICONS&quot;: &quot;03819D64&quot;,
        ///    &quot;HUD_COLOR_CONFIG&quot;: &quot;03819DD4&quot;,
        ///    &quot;ITEM_OVERRIDE_COUNT&quot;: &quot;0381A4BC&quot;,
        ///    &quot;ITEM_OVERRIDE_ENTRIES&quot;: &quot;0381A878&quot;,
        ///    &quot;KALEIDOPAYLOAD_END&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string symbols {
            get {
                return ResourceManager.GetString("symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZoraEgg {
            get {
                object obj = ResourceManager.GetObject("ZoraEgg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;ZORA_EGG_BASELINE_ADD&quot;: &quot;80B319CC&quot;,
        ///    &quot;ZORA_EGG_BASELINE_SUBTRACT&quot;: &quot;80B32214&quot;
        ///}
        ///.
        /// </summary>
        internal static string ZoraEgg_symbols {
            get {
                return ResourceManager.GetString("ZoraEgg_symbols", resourceCulture);
            }
        }
    }
}
