//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Randomizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class mods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Randomizer.Resources.mods", typeof(mods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] add_bombchu_drops {
            get {
                object obj = ResourceManager.GetObject("add_bombchu_drops", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] byo_ammo {
            get {
                object obj = ResourceManager.GetObject("byo_ammo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chest_table {
            get {
                object obj = ResourceManager.GetObject("chest_table", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chestgame_minimap {
            get {
                object obj = ResourceManager.GetObject("chestgame_minimap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] climb_most_surfaces {
            get {
                object obj = ResourceManager.GetObject("climb_most_surfaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cm_cs {
            get {
                object obj = ResourceManager.GetObject("cm_cs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] collectable_table {
            get {
                object obj = ResourceManager.GetObject("collectable_table", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] de_1 {
            get {
                object obj = ResourceManager.GetObject("de_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] de_2 {
            get {
                object obj = ResourceManager.GetObject("de_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] de_3 {
            get {
                object obj = ResourceManager.GetObject("de_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] de_4 {
            get {
                object obj = ResourceManager.GetObject("de_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] de_5 {
            get {
                object obj = ResourceManager.GetObject("de_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] death_moon_crash {
            get {
                object obj = ResourceManager.GetObject("death_moon_crash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] death_reduces_max_hearts {
            get {
                object obj = ResourceManager.GetObject("death_reduces_max_hearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dm_1 {
            get {
                object obj = ResourceManager.GetObject("dm_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dm_2 {
            get {
                object obj = ResourceManager.GetObject("dm_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dm_3 {
            get {
                object obj = ResourceManager.GetObject("dm_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dm_4 {
            get {
                object obj = ResourceManager.GetObject("dm_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon_fairy_npc_hint {
            get {
                object obj = ResourceManager.GetObject("dungeon_fairy_npc_hint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] enable_sunssong {
            get {
                object obj = ResourceManager.GetObject("enable_sunssong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] enemy_max_health {
            get {
                object obj = ResourceManager.GetObject("enemy_max_health", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fairies_chests_only {
            get {
                object obj = ResourceManager.GetObject("fairies_chests_only", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] faster_bank_text {
            get {
                object obj = ResourceManager.GetObject("faster_bank_text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] faster_bank_text_restore_intro {
            get {
                object obj = ResourceManager.GetObject("faster_bank_text_restore_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fierce_deity_anywhere {
            get {
                object obj = ResourceManager.GetObject("fierce_deity_anywhere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] file_select {
            get {
                object obj = ResourceManager.GetObject("file_select", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_clock_speed {
            get {
                object obj = ResourceManager.GetObject("fix_clock_speed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_collectable_flags {
            get {
                object obj = ResourceManager.GetObject("fix_collectable_flags", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_cow_bottle_check {
            get {
                object obj = ResourceManager.GetObject("fix_cow_bottle_check", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_deku_drowning {
            get {
                object obj = ResourceManager.GetObject("fix_deku_drowning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_deku_playground_softlock {
            get {
                object obj = ResourceManager.GetObject("fix_deku_playground_softlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_deku_princess {
            get {
                object obj = ResourceManager.GetObject("fix_deku_princess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_downgrades {
            get {
                object obj = ResourceManager.GetObject("fix_downgrades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_epona {
            get {
                object obj = ResourceManager.GetObject("fix_epona", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_fairies {
            get {
                object obj = ResourceManager.GetObject("fix_fairies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_fd_mask_reset {
            get {
                object obj = ResourceManager.GetObject("fix_fd_mask_reset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_fisherman {
            get {
                object obj = ResourceManager.GetObject("fix_fisherman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_great_bay_clear_mikau {
            get {
                object obj = ResourceManager.GetObject("fix_great_bay_clear_mikau", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_item_checks {
            get {
                object obj = ResourceManager.GetObject("fix_item_checks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_kafei {
            get {
                object obj = ResourceManager.GetObject("fix_kafei", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_keg_check {
            get {
                object obj = ResourceManager.GetObject("fix_keg_check", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_link_1 {
            get {
                object obj = ResourceManager.GetObject("fix_link_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_link_2 {
            get {
                object obj = ResourceManager.GetObject("fix_link_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_link_3 {
            get {
                object obj = ResourceManager.GetObject("fix_link_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_moon_trial_access {
            get {
                object obj = ResourceManager.GetObject("fix_moon_trial_access", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_music {
            get {
                object obj = ResourceManager.GetObject("fix_music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_notebook_madame_aroma {
            get {
                object obj = ResourceManager.GetObject("fix_notebook_madame_aroma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_object_stk2_zbuffer {
            get {
                object obj = ResourceManager.GetObject("fix_object_stk2_zbuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_ocarina_checks {
            get {
                object obj = ResourceManager.GetObject("fix_ocarina_checks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_piece_of_heart_message {
            get {
                object obj = ResourceManager.GetObject("fix_piece_of_heart_message", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_shop_businessscrub_bluepotion {
            get {
                object obj = ResourceManager.GetObject("fix_shop_businessscrub_bluepotion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_shop_businessscrub_greenpotion {
            get {
                object obj = ResourceManager.GetObject("fix_shop_businessscrub_greenpotion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_shop_businessscrub_magicbean {
            get {
                object obj = ResourceManager.GetObject("fix_shop_businessscrub_magicbean", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_shop_curiosity_bigbombbag {
            get {
                object obj = ResourceManager.GetObject("fix_shop_curiosity_bigbombbag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_shop_gorman_milk {
            get {
                object obj = ResourceManager.GetObject("fix_shop_gorman_milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_shop_milkbar {
            get {
                object obj = ResourceManager.GetObject("fix_shop_milkbar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_shop_witch_bluepotion {
            get {
                object obj = ResourceManager.GetObject("fix_shop_witch_bluepotion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_skulltula_tokens {
            get {
                object obj = ResourceManager.GetObject("fix_skulltula_tokens", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_song_of_healing {
            get {
                object obj = ResourceManager.GetObject("fix_song_of_healing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_song_of_time {
            get {
                object obj = ResourceManager.GetObject("fix_song_of_time", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_sword_song_of_time {
            get {
                object obj = ResourceManager.GetObject("fix_sword_song_of_time", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fix_town_fairy_text {
            get {
                object obj = ResourceManager.GetObject("fix_town_fairy_text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] floor_1 {
            get {
                object obj = ResourceManager.GetObject("floor_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] floor_2 {
            get {
                object obj = ResourceManager.GetObject("floor_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] floor_3 {
            get {
                object obj = ResourceManager.GetObject("floor_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] floor_4 {
            get {
                object obj = ResourceManager.GetObject("floor_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] free_garo_hints {
            get {
                object obj = ResourceManager.GetObject("free_garo_hints", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garo_hints {
            get {
                object obj = ResourceManager.GetObject("garo_hints", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gi_table {
            get {
                object obj = ResourceManager.GetObject("gi_table", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] giant_mask_anywhere {
            get {
                object obj = ResourceManager.GetObject("giant_mask_anywhere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gossip_hints_free {
            get {
                object obj = ResourceManager.GetObject("gossip_hints_free", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gossip_hints_tolerant {
            get {
                object obj = ResourceManager.GetObject("gossip_hints_tolerant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hookshot_any_surface {
            get {
                object obj = ResourceManager.GetObject("hookshot_any_surface", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] improved_camera {
            get {
                object obj = ResourceManager.GetObject("improved_camera", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] init_file {
            get {
                object obj = ResourceManager.GetObject("init_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] instant_pictobox {
            get {
                object obj = ResourceManager.GetObject("instant_pictobox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] instrumentset_patch {
            get {
                object obj = ResourceManager.GetObject("instrumentset_patch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] key_boss_open {
            get {
                object obj = ResourceManager.GetObject("key_boss_open", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] key_boss_sot {
            get {
                object obj = ResourceManager.GetObject("key_boss_sot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] key_small_open {
            get {
                object obj = ResourceManager.GetObject("key_small_open", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lenient_goron_spikes {
            get {
                object obj = ResourceManager.GetObject("lenient_goron_spikes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] logo_text {
            get {
                object obj = ResourceManager.GetObject("logo_text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] misc_changes {
            get {
                object obj = ResourceManager.GetObject("misc_changes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] misc_changes_restore_swamp_owl {
            get {
                object obj = ResourceManager.GetObject("misc_changes_restore_swamp_owl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] moveaudiostatebytes {
            get {
                object obj = ResourceManager.GetObject("moveaudiostatebytes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] movement_1 {
            get {
                object obj = ResourceManager.GetObject("movement_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] movement_2 {
            get {
                object obj = ResourceManager.GetObject("movement_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] movement_3 {
            get {
                object obj = ResourceManager.GetObject("movement_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] movement_4 {
            get {
                object obj = ResourceManager.GetObject("movement_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] postman_testing {
            get {
                object obj = ResourceManager.GetObject("postman_testing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] quick_text {
            get {
                object obj = ResourceManager.GetObject("quick_text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rainbow_tatl {
            get {
                object obj = ResourceManager.GetObject("rainbow_tatl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] reloc_audio {
            get {
                object obj = ResourceManager.GetObject("reloc_audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] remove_fanfares {
            get {
                object obj = ResourceManager.GetObject("remove_fanfares", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] remove_minor_music {
            get {
                object obj = ResourceManager.GetObject("remove_minor_music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] remove_morning_music {
            get {
                object obj = ResourceManager.GetObject("remove_morning_music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] remove_tatl_interrupts {
            get {
                object obj = ResourceManager.GetObject("remove_tatl_interrupts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] replace_gi_table {
            get {
                object obj = ResourceManager.GetObject("replace_gi_table", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_fierce_deity {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_fierce_deity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_fix_0thday_4thday_town_shooting {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_fix_0thday_4thday_town_shooting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_fix_0thday_erase {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_fix_0thday_erase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_fix_4thday_deku_playground {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_fix_4thday_deku_playground", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_fix_4thday_gossip {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_fix_4thday_gossip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_fix_4thday_mayor {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_fix_4thday_mayor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_fix_goron_bow {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_fix_goron_bow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_index_warp {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_index_warp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_sodt {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_sodt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safer_glitches_tatl_text_zero_fourth_day {
            get {
                object obj = ResourceManager.GetObject("safer_glitches_tatl_text_zero_fourth_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] short_cutscenes {
            get {
                object obj = ResourceManager.GetObject("short_cutscenes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_don_gero {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_don_gero", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_goht_intro {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_goht_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_gomess_intro {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_gomess_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_gv_owl {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_gv_owl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_gyorg_intro {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_gyorg_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_hold_a_auto_text {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_hold_a_auto_text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_igos_intro {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_igos_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_jim_running {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_jim_running", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_kotake {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_kotake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_majora_intro {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_majora_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_odolwa_intro {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_odolwa_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_princess_delivery {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_princess_delivery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_sun_mask {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_sun_mask", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_tingle {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_tingle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_twinmold_intro {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_twinmold_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shorten_cutscene_wart_intro {
            get {
                object obj = ResourceManager.GetObject("shorten_cutscene_wart_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sonata_check_gentle_throw {
            get {
                object obj = ResourceManager.GetObject("sonata_check_gentle_throw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] speedup_babycucco_minimap {
            get {
                object obj = ResourceManager.GetObject("speedup_babycucco_minimap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] speedup_bank {
            get {
                object obj = ResourceManager.GetObject("speedup_bank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] speedup_beavers {
            get {
                object obj = ResourceManager.GetObject("speedup_beavers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] speedup_dampe {
            get {
                object obj = ResourceManager.GetObject("speedup_dampe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] speedup_dograce {
            get {
                object obj = ResourceManager.GetObject("speedup_dograce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] speedup_labfish {
            get {
                object obj = ResourceManager.GetObject("speedup_labfish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] standing_hearts {
            get {
                object obj = ResourceManager.GetObject("standing_hearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] take_damage_from_caught {
            get {
                object obj = ResourceManager.GetObject("take_damage_from_caught", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] take_damage_from_dexihands {
            get {
                object obj = ResourceManager.GetObject("take_damage_from_dexihands", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] take_damage_from_dog {
            get {
                object obj = ResourceManager.GetObject("take_damage_from_dog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] take_damage_from_gibdo_immediately {
            get {
                object obj = ResourceManager.GetObject("take_damage_from_gibdo_immediately", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] take_damage_from_goron {
            get {
                object obj = ResourceManager.GetObject("take_damage_from_goron", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] take_damage_from_void {
            get {
                object obj = ResourceManager.GetObject("take_damage_from_void", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] take_damage_while_shielding {
            get {
                object obj = ResourceManager.GetObject("take_damage_while_shielding", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tatl_remains_hint {
            get {
                object obj = ResourceManager.GetObject("tatl_remains_hint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] title_screen {
            get {
                object obj = ResourceManager.GetObject("title_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] update_chest_cutscene {
            get {
                object obj = ResourceManager.GetObject("update_chest_cutscene", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] update_chests {
            get {
                object obj = ResourceManager.GetObject("update_chests", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] update_kafei_mask_icon {
            get {
                object obj = ResourceManager.GetObject("update_kafei_mask_icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] update_remains_required {
            get {
                object obj = ResourceManager.GetObject("update_remains_required", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] update_trade_scrubs {
            get {
                object obj = ResourceManager.GetObject("update_trade_scrubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ztargetinghold {
            get {
                object obj = ResourceManager.GetObject("ztargetinghold", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
